# schema defition for FWJR production documents

fwjr = \
{'meta_data': {'agent_ver': '1.0.14.pre5',
               'fwjr_id': '1-0',
               'crab_id': 'crab',
               'crab_exit_code': 101,
               'host': 'test.fnal.gov',
               # TODO: need to specify other fields: total_cpu, hs06, etc
               'wn_name': "testhost1234.cern.ch",
               'jobtype': "Processing",
               'jobstate': "success", 
               'ts': 1456500229},
 'LFNArray': ['/store/test/blah.root',
              '/store/unmerged/blah.root',
              '/lfn/fallbackfile.root', '/lfn/skipedfile.root'],
 'LFNArrayRef': ['fallbackFiles',
                 'outputLFNs',
                 'lfn',
                 'skippedFiles',
                 'inputLFNs'],
 'PFNArray': ['root://test.ch/blah.root',
              'root://test.ch/blah2.root',
              ],
 'PFNArrayRef': ['inputPFNs', 'outputPFNs', 'pfn'],  # list of keys whose value is referencing fileArray index
 
 'Campaign': 'TestCampaign',
 
 'PrepID': 'TestPrepID',
 
 'steps': [{'name': 'cmsRun1',
             #'analysis': {}, 
             #'cleanup': {},
             #'logs': {},
             'errors': [
                   {
                       "details": "Failed badly.",
                       "type": "Fatal Exception",
                       "exitCode": 8001
                   }
               ],
             'input': [{'catalog': '',
                        'events': 6893,
                        'guid': 'E8099605-8853-E011-A848-0030487A18F2',
                        'input_source_class': 'PoolSource',
                        'input_type': 'primaryFiles',
                        'lfn': 0,
                        'module_label': 'source',
                        'pfn': 0,
                        'runs': [{'lumis': [164, 165],
                                  'runNumber': 160960}]}],
             'output': [{'StageOutCommand': 'rfcp-CERN',
                         'acquisitionEra': 'CMSSW_7_0_0_pre11',
                         'adler32': 'e503b8b9',
                         'applicationName': 'cmsRun',
                         'applicationVersion': 'CMSSW_7_0_0_pre11',
                         'async_dest': '',
                         'branch_hash': 'c1e135af4ac2eb2b803bb6487be2c80f',
                         'catalog': '',
                         'cksum': '2641269665',
                         'configURL': 'https://couch.config.ch5f4811e9ccd63d563cd62572350f0db8',
                         'events': 0,
                         'globalTag': 'GR_R_62_V3::All',
                         'guid': 'ECCFE421-08CB-E511-9F4C-02163E017804',
                         'inputDataset': '/Cosmics/Run2011A-v1/RAW',
                         'inputLFNs': [0],
                         'inputPFNs': [0],
                         'location': '',
                         'merged': False,
                         'module_label': 'ALCARECOStreamDtCalib',
                         'ouput_module_class': 'PoolOutputModule',
                         'outputDataset': '/test/proc/ALCARECO',
                         'outputLFNs': [1],
                         'outputPFNs': [1],
                         'prep_id': '',
                         'processingStr': 'RECOCOSD_TaskChain_Data_pile_up_test',
                         'processingVer': 1,
                         'runs': [{'lumis': [164, 165],
                                   'eventsPerLumi': [100, 150],
                                   'runNumber': 160960}],
                         'size': 647376,
                         'validStatus': 'PRODUCTION',
                         "SEName": "srm-cms.cern.ch",
                         "PNN": "T2_CERN_CH",
                         "GUID": '',
                         "StageOutCommand": "srmv2-lcg"}],
              'performance': {
                  "multicore": {
                  },
                  "storage": {
                    "readAveragekB": 77.8474891246,
                    "readCachePercentageOps": 0.0,
                    'readMBSec': 0.0438598972596,
                    'readMaxMSec': 4832.84,
                    'readNumOps': 97620.0,
                    'readPercentageOps': 1.00032780168,
                    'readTotalMB': 7423.792,    
                    'readTotalSecs': 0.0,
                    'writeTotalMB': 357.624,
                    'writeTotalSecs': 575158.0
                   },
                   "memory": {
                       "PeakValueRss": 0.0,
                       "PeakValueVsize": 0.0
                   },
                   "cpu": {
                       "TotalJobCPU": 0.39894,
                       "AvgEventCPU": -2.0, # for ("-nan")
                       "MaxEventCPU": 0.0,
                       "AvgEventTime": -1.0, # for ("inf")
                       "MinEventCPU": 0.0,
                       "TotalEventCPU": 0.0,
                       "TotalJobTime": 26.4577,
                       "MinEventTime": 0.0,
                       "MaxEventTime": 0.0,
                       'EventThroughput': 0.0,
                       'TotalLoopCPU': 0.0,
                       'TotalInitTime': 0.0,
                       'TotalInitCPU': 0.0,
                       'NumberOfThreads': 0,
                       'NumberOfStreams': 0
                   },
                   "cmssw": {
                       "SystemMemory": {
                            "MemTotal": 131762060,
                            "Hugepagesize": 2048,
                            "WritebackTmp": 0,
                            "SwapCached": 339856,
                            "MemFree": 637104,
                            "CmaTotal": 0,
                            "Inactive(file)": 53824644,
                            "CommitLimit": 197623744,
                            "Active": 65631416,
                            "HugePages_Surp": 0,
                            "DirectMap1G": 78643200,
                            "Mapped": 171568,
                            "VmallocUsed": 919696,
                            "HardwareCorrupted": 0,
                            "Inactive": 59008012,
                            "HugePages_Rsvd": 0,
                            "Shmem": 40760,
                            "CmaFree": 0,
                            "Active(file)": 50807876,
                            "KernelStack": 51360,
                            "Dirty": 46068,
                            "Unevictable": 2376,
                            "SUnreclaim": 558160,
                            "Mlocked": 2376,
                            "Active(anon)": 14823540,
                            "Slab": 3561680,
                            "NFS_Unstable": 0,
                            "SReclaimable": 3003520,
                            "Percpu": 33024,
                            "DirectMap4k": 632192,
                            "Buffers": 1884,
                            "Bounce": 0,
                            "PageTables": 172264,
                            "Committed_AS": 40767560,
                            "Writeback": 32,
                            "DirectMap2M": 56942592,
                            "SwapTotal": 131742716,
                            "HugePages_Total": 0,
                            "Inactive(anon)": 5183368,
                            "Cached": 104675740,
                            "VmallocTotal": -1,
                            "AnonPages": 19907516,
                            "MemAvailable": 107646680,
                            "SwapFree": 111606780,
                            "HugePages_Free": 0,
                            "AnonHugePages": 8192,
                            "VmallocChunk": -68268032
                        },
                       "SystemCPU": {
                            "CPUModels": 'Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz',
                            "totalCPUs": 40,
                            "averageCoreSpeed": 2400.24,
                            "cpusetCount": 40
                        },
                       "Timing": {
                            "TotalJobCPU": 9439.96,
                            "TotalLoopCPU": 9435.32,
                            "EventThroughput": 0.0104264,
                            "MaxEventTime": 124.671,
                            "NumberOfThreads": 1,
                            "AvgEventTime": 95.3874,
                            "TotalJobTime": 9598.76,
                            "NumberOfStreams": 1,
                            "MinEventTime": 65.0726
                        },
                       "StorageStatistics": {
                            "Timing-file-prefetch-numSuccessfulOperations": 0,
                            "Timing-file-read-totalMegabytes": 1421.94,
                            "Timing-tstoragefile-writeActual-maxMsecs": 74.7119,
                            "Timing-file-read-maxMsecs": 559.746,
                            "Timing-tstoragefile-write-numOperations": 3802,
                            "Timing-tstoragefile-writeViaCache-minMsecs": 0,
                            "Parameter-untracked-bool-stats": True,
                            "Timing-tstoragefile-close-numSuccessfulOperations": 1,
                            "Timing-tstoragefile-flush-totalMegabytes": 0,
                            "Timing-tstoragefile-read-numOperations": 188931,
                            "Timing-file-writev-totalMsecs": 0,
                            "Timing-file-flush-numOperations": 2,
                            "Timing-tstoragefile-stat-totalMsecs": 0.043538,
                            "Timing-file-write-maxMsecs": 74.7106,
                            "Timing-tstoragefile-read-maxMsecs": 559.748,
                            "Timing-tstoragefile-stat-numOperations": 4,
                            "Timing-file-position-minMsecs": 0.000803,
                            "Timing-tstoragefile-writeActual-totalMegabytes": 128.401,
                            "Timing-tstoragefile-writeViaCache-totalMsecs": 0,
                            "Timing-file-construct-numOperations": 3,
                            "Timing-tstoragefile-read-minMsecs": 0.001331,
                            "Timing-file-flush-totalMsecs": 20.7024,
                            "Timing-file-writev-maxMsecs": 0,
                            "Timing-tstoragefile-readActual-maxMsecs": 559.748,
                            "Timing-tstoragefile-readActual-numSuccessfulOperations": 188931,
                            "Timing-tstoragefile-readActual-minMsecs": 0.001202,
                            "Timing-file-writev-numOperations": 0,
                            "Timing-tstoragefile-construct-totalMsecs": 328.408,
                            "Timing-tstoragefile-seek-numSuccessfulOperations": 192733,
                            "Timing-tstoragefile-writeActual-numOperations": 3802,
                            "Timing-file-flush-maxMsecs": 19.886,
                            "Timing-tstoragefile-readActual-numOperations": 188931,
                            "Timing-file-prefetch-minMsecs": 0,
                            "Parameter-untracked-string-readHint": 'auto-detect',
                            "Timing-tstoragefile-flush-totalMsecs": 20.8532,
                            "Timing-file-writev-totalMegabytes": 0,
                            "Timing-tstoragefile-stat-totalMegabytes": 0,
                            "Timing-tstoragefile-flush-numOperations": 2,
                            "Timing-tstoragefile-read-totalMegabytes": 1421.94,
                            "Timing-tstoragefile-flush-numSuccessfulOperations": 2,
                            "Parameter-untracked-bool-prefetching": False,
                            "Timing-file-construct-totalMegabytes": 0,
                            "Timing-file-prefetch-totalMsecs": 0,
                            "Timing-file-readv-numSuccessfulOperations": 0,
                            "Timing-file-open-minMsecs": 0.258973,
                            "Timing-tstoragefile-flush-maxMsecs": 19.8881,
                            "Timing-file-position-maxMsecs": 0.465223,
                            "Timing-tstoragefile-writeActual-numSuccessfulOperations": 3802,
                            "Timing-tstoragefile-construct-minMsecs": 20.6566,
                            "Timing-file-construct-numSuccessfulOperations": 3,
                            "Timing-file-flush-minMsecs": 0.816393,
                            "Timing-file-close-maxMsecs": 0.396446,
                            "Timing-file-write-numSuccessfulOperations": 3802,
                            "Timing-file-readv-maxMsecs": 0,
                            "Timing-tstoragefile-writeViaCache-numOperations": 3802,
                            "Timing-file-write-totalMegabytes": 128.401,
                            "Timing-tstoragefile-writeActual-totalMsecs": 294.318,
                            "Timing-file-writev-numSuccessfulOperations": 0,
                            "Timing-tstoragefile-read-totalMsecs": 22283.6,
                            "Timing-tstoragefile-stat-maxMsecs": 0.025108,
                            "Timing-file-prefetch-totalMegabytes": 0,
                            "Timing-tstoragefile-flush-minMsecs": 0.965192,
                            "Timing-file-read-numSuccessfulOperations": 188931,
                            "Timing-file-construct-totalMsecs": 0.004365,
                            "Timing-file-readv-numOperations": 0,
                            "Timing-file-open-totalMegabytes": 0,
                            "Timing-tstoragefile-construct-totalMegabytes": 0,
                            "Timing-file-open-numOperations": 3,
                            "Timing-tstoragefile-seek-numOperations": 192733,
                            "Timing-file-readv-totalMsecs": 0,
                            "Parameter-untracked-bool-enabled": True,
                            "Timing-file-position-totalMsecs": 439.549,
                            "Timing-file-open-totalMsecs": 4.38491,
                            "Timing-file-read-totalMsecs": 22196.9,
                            "Timing-tstoragefile-construct-numSuccessfulOperations": 3,
                            "Timing-file-prefetch-numOperations": 0,
                            "Timing-tstoragefile-readActual-totalMsecs": 22246.6,
                            "Timing-file-read-minMsecs": 0.001066,
                            "Timing-file-open-numSuccessfulOperations": 3,
                            "Timing-file-close-numSuccessfulOperations": 1,
                            "Timing-tstoragefile-close-numOperations": 1,
                            "Timing-tstoragefile-write-numSuccessfulOperations": 3802,
                            "Timing-tstoragefile-seek-totalMegabytes": 0,
                            "Timing-file-close-totalMsecs": 0.396446,
                            "Timing-file-close-totalMegabytes": 0,
                            "ROOT-tfile-read-totalMegabytes": 1.22716,
                            "Timing-tstoragefile-write-totalMsecs": 295.277,
                            "Timing-tstoragefile-write-totalMegabytes": 128.401,
                            "Timing-tstoragefile-close-totalMsecs": 0.399809,
                            "Timing-file-position-totalMegabytes": 0,
                            "Timing-tstoragefile-construct-numOperations": 3,
                            "Timing-file-construct-maxMsecs": 0.003897,
                            "Timing-tstoragefile-writeViaCache-maxMsecs": 0,
                            "Timing-tstoragefile-writeViaCache-totalMegabytes": 0,
                            "Parameter-untracked-string-cacheHint": 'auto-detect',
                            "Timing-file-readv-totalMegabytes": 0,
                            "Timing-file-position-numSuccessfulOperations": 192761,
                            "Timing-file-close-numOperations": 1,
                            "Timing-tstoragefile-seek-totalMsecs": 492.793,
                            "Timing-tstoragefile-close-totalMegabytes": 0,
                            "Timing-tstoragefile-write-maxMsecs": 74.7126,
                            "Timing-file-write-numOperations": 3802,
                            "Timing-tstoragefile-read-numSuccessfulOperations": 188931,
                            "ROOT-tfile-write-totalMegabytes": 0,
                            "Timing-file-flush-totalMegabytes": 0,
                            "Timing-tstoragefile-writeActual-minMsecs": 0.002506,
                            "Timing-file-read-numOperations": 188931,
                            "Timing-file-writev-minMsecs": 0,
                            "Timing-tstoragefile-writeViaCache-numSuccessfulOperations": 0,
                            "Timing-tstoragefile-seek-maxMsecs": 0.469834,
                            "Timing-tstoragefile-seek-minMsecs": 0.000904,
                            "Timing-file-close-minMsecs": 0.396446,
                            "Timing-tstoragefile-readActual-totalMegabytes": 1421.94,
                            "Timing-file-flush-numSuccessfulOperations": 2,
                            "Timing-tstoragefile-stat-minMsecs": 0.004015,
                            "Timing-tstoragefile-close-minMsecs": 0.399809,
                            "Timing-file-write-minMsecs": 0.002357,
                            "Timing-tstoragefile-construct-maxMsecs": 199.328,
                            "Timing-file-readv-minMsecs": 0,
                            "Timing-file-prefetch-maxMsecs": 0,
                            "Timing-file-write-totalMsecs": 293.452,
                            "Timing-tstoragefile-write-minMsecs": 0.002677,
                            "Timing-tstoragefile-close-maxMsecs": 0.399809,
                            "Timing-file-open-maxMsecs": 2.21925,
                            "Timing-file-position-numOperations": 192761,
                            "Timing-file-construct-minMsecs": 0.000206,
                            "Timing-tstoragefile-stat-numSuccessfulOperations": 4
                        },
                        "ApplicationMemory": {
                            "LargestIncreaseRssEvent-a-COUNT": 2,
                            "ThirdLargestVsizeEventT3-b-RUN": 1,
                            "HEAP_ARENA_SIZE_BYTES": 0,
                            "LargestRssEvent-a-COUNT": 2,
                            "SecondLargestRssEvent-a-COUNT": 6,
                            "LargestVsizeEventT1-c-EVENT": 176,
                            "SecondLargestVsizeEventT2-c-EVENT": 177,
                            "LargeVsizeIncreaseEventR1-f-RSS": 538.473,
                            "HEAP_UNUSED_BYTES": 0,
                            "ThirdLargestRssEvent-b-RUN": 1,
                            "LargestIncreaseRssEvent-b-RUN": 1,
                            "HEAP_MAPPED_N_CHUNKS": 0,
                            "LargestIncreaseRssEvent-d-VSIZE": 983.602,
                            "LargeVsizeIncreaseEventL1-e-DELTV": 0,
                            "LargestVsizeEventT1-b-RUN": 1,
                            "ThirdLargestVsizeEventT3-a-COUNT": 78,
                            "LargestVsizeEventT1-f-RSS": 538.473,
                            "LargestRssEvent-d-VSIZE": 983.602,
                            "LargestRssEvent-f-RSS": 557.59,
                            "LargestVsizeIncreaseEvent-d-VSIZE": 983.602,
                            "SecondLargestRssEvent-e-DELTV": 22,
                            "LargeVsizeIncreaseEventR1-b-RUN": 1,
                            "LargeVsizeIncreaseEventL1-a-COUNT": 1,
                            "LargeVsizeIncreaseEventL1-c-EVENT": 101,
                            "ThirdLargestVsizeEventT3-d-VSIZE": 1105.32,
                            "LargeVsizeIncreaseEventR2-c-EVENT": 106,
                            "LargeVsizeIncreaseEventR1-a-COUNT": 76,
                            "HEAP_USED_BYTES": 0,
                            "LargestIncreaseRssEvent-f-RSS": 557.59,
                            "AverageGrowthRateRss": 3.50785,
                            "ThirdLargestVsizeEventT3-e-DELTV": 0,
                            "LargeVsizeIncreaseEventR1-e-DELTV": 26,
                            "HEAP_MAPPED_SIZE_BYTES": 0,
                            "SecondLargestVsizeEventT2-b-RUN": 1,
                            "LargeVsizeIncreaseEventR2-f-RSS": 549.453,
                            "SecondLargestRssEvent-f-RSS": 549.453,
                            "LargestVsizeIncreaseEvent-e-DELTV": 56.7578,
                            "SecondLargestVsizeEventT2-d-VSIZE": 1105.32,
                            "ThirdLargestRssEvent-d-VSIZE": 1079.32,
                            "SecondLargestRssEvent-c-EVENT": 106,
                            "SecondLargestVsizeEventT2-a-COUNT": 77,
                            "SecondLargestRssEvent-d-VSIZE": 1011.2,
                            "LargestVsizeIncreaseEvent-a-COUNT": 2,
                            "LargeVsizeIncreaseEventL1-d-VSIZE": 926.844,
                            "LargestVsizeEventT1-e-DELTV": 26,
                            "LargeVsizeIncreaseEventR2-e-DELTV": 22,
                            "LargestRssEvent-e-DELTV": 56.7578,
                            "HEAP_TOP_FREE_BYTES": 0,
                            "LargeVsizeIncreaseEventL1-f-RSS": 508.34,
                            "ThirdLargestRssEvent-e-DELTV": 0,
                            "LargestRssEvent-c-EVENT": 102,
                            "LargestRssEvent-b-RUN": 1,
                            "ThirdLargestVsizeEventT3-f-RSS": 537.445,
                            "LargeVsizeIncreaseEventR2-a-COUNT": 6,
                            "SecondLargestRssEvent-b-RUN": 1,
                            "LargestVsizeEventT1-a-COUNT": 76,
                            "PeakValueVsize": 1105.32,
                            "HEAP_ARENA_N_UNUSED_CHUNKS": 1,
                            "ThirdLargestRssEvent-f-RSS": 543.348,
                            "LargestIncreaseRssEvent-e-DELTV": 56.7578,
                            "LargestVsizeEventT1-d-VSIZE": 1105.32,
                            "LargestVsizeIncreaseEvent-f-RSS": 557.59,
                            "PeakValueRss": 557.59,
                            "ThirdLargestRssEvent-a-COUNT": 70,
                            "LargestVsizeIncreaseEvent-b-RUN": 1,
                            "LargeVsizeIncreaseEventR1-c-EVENT": 176,
                            "LargeVsizeIncreaseEventR1-d-VSIZE": 1105.32,
                            "ThirdLargestRssEvent-c-EVENT": 170,
                            "ThirdLargestVsizeEventT3-c-EVENT": 178,
                            "SecondLargestVsizeEventT2-e-DELTV": 0,
                            "LargeVsizeIncreaseEventR2-d-VSIZE": 1011.2,
                            "AverageGrowthRateVsize": 5.82414,
                            "LargeVsizeIncreaseEventR2-b-RUN": 1,
                            "SecondLargestVsizeEventT2-f-RSS": 531.008,
                            "LargeVsizeIncreaseEventL1-b-RUN": 1,
                            "LargestIncreaseRssEvent-c-EVENT": 102,
                            "LargestVsizeIncreaseEvent-c-EVENT": 102
                        }
                   }
              },
              'site': 'T2_CH_CERN',
              'start': 1454569735,
              'status': 0,
              'stop': 1454569736}
            ],
'fallbackFiles': [0],
'skippedFiles': [1],
'task': '/workflow_name/RECOCOSD'}
